name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Set up Maven settings
        uses: s4u/maven-settings-action@v4.0.0
        with:
          servers: '[{"id": "central", "username": "${{ secrets.SONATYPE_USERNAME }}", "password": "${{ secrets.SONATYPE_PASSWORD }}"}]'

      - name: Import GPG key
        run: |
          echo "$MAVEN_GPG_KEY" | gpg --batch --import
        env:
          MAVEN_GPG_KEY: ${{ secrets.MAVEN_GPG_KEY }}

      - name: Verify GPG key
        run: gpg --list-secret-keys

      - name: Publish to Maven Central
        run: mvn -B deploy
        env:
          MAVEN_GPG_KEY: ${{ secrets.MAVEN_GPG_KEY }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
          MAVEN_GPG_KEY_FINGERPRINT: ${{ secrets.MAVEN_GPG_KEY_FINGERPRINT }}
